.SUFFIXES:
.SUFFIXES: .o .cpp	

#CC=gcc
#CC=CC -mips4 -64
#CC=gcc -mcpu=ultrasparc
#INCLUDE = -I. -I/usr/local/ssl/include -I/usr/users/sya/sk13/openssl/include -I/home/imis/mix/openssl64/include -I/sun/ikt/sk13/openssl/include
INCLUDE = -I. -I/usr/users/sya/sk13/openssl/include -I/home/imis/mix/openssl64/include -I/sun/ikt/sk13/openssl/include
#LIBS	= -L/usr/local/ssl/lib -L/usr/users/sya/sk13/openssl/lib -L/home/imis/mix/openssl64/lib -L/sun/ikt/sk13/openssl/lib ./popt/popt.a ./httptunnel/httptunnel.a ./xml/xml.a -lcrypto -lpthread
LIBDIR= -L/usr/users/sya/sk13/openssl/lib -L/home/imis/mix/openssl64/lib -L/sun/ikt/sk13/openssl/lib -L/usr/local/lib
LIBS	= ./popt/popt.a ./xml/xml.a ./aes/libaes.a -lcrypto 
#CPPFLAGS =-O3 -Wall 
#CPPFLAGS =-O3 -D_REENTRANT
#DEBUG =-D_DEBUG -g
MAKE=make -f Makefile.old

OBJS_ALL=CASocket.o\
	CAQueue.o\
	CASingleSocketGroup.o\
	CASocketGroup.o\
	CASocketAddrINet.o\
	CASocketAddrUnix.o\
	CASocketList.o\
	CACmdLnOptions.o\
	CAMsg.o\
	CAMuxSocket.o\
	CAFirstMixChannelList.o\
	CAIPList.o\
	CASymCipher.o\
	CAASymCipher.o\
	CAInfoService.o\
	CASignature.o\
	CABase64.o\
	CAUtil.o\
	CADatagramSocket.o\
	CARoundTripTime.o\
	CAMix.o\
	CAFirstMix.o\
	CALastMix.o\
	CAMiddleMix.o\
	CALocalProxy.o\
	CACacheLoadBalancing.o\
	proxytest.o

OBJS=$(OBJS_ALL)

.cpp.o:
	$(CC) -c $(CPPFLAGS) $(INCLUDE) $(DEBUG) $< $(LDFLAGS) -o $@


all: 
	@echo 'Please select a target:'
	@echo 'linux-x86-gcc, linux-x86-gcc-async,' 
	@echo 'linux-x86-gcc-static, linux-x86-gcc-debug,'
	@echo 'solaris-ultrasparc-gcc, irix-64-cc, irix-64-cc-prot2, irix-64-cc-async'


linux-x86-gcc:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-Wall -Wcast-align -fomit-frame-pointer -march=i686 -O3 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-async:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-D_ASYNC -D_REENTRANT -Wall -Wcast-align -Winline -finline-functions -fomit-frame-pointer -march=i686 -O3' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++ ' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-async-static:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-static -D_ASYNC -D_REENTRANT -Wall -Wcast-align -fomit-frame-pointer -march=i686 -O3' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-k6-gcc-async:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-D_ASYNC -D_REENTRANT -Wall -Wcast-align -Winline -finline-functions -fomit-frame-pointer -march=k6 -O3' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-debug-async:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-ggdb -D_DEBUG -D_REENTRANT -D_ASYNC -Wall -Wcast-align -march=i686' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-prof-async:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-static -D_ASYNC -D_REENTRANT -Wall -Wcast-align -march=i686 -O3 -g -p -pg -a' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-fnc-async:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-static -D_ASYNC -D_REENTRANT -Wall -Wcast-align -march=i686 -O3 -g -finstrument-functions' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=-lm -lbfd -liberty -ldl $(LIBS) -lpthread -lfnccheck -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib -L$(HOME)/fncheck/lib' _all_aes 

linux-x86-gcc-debug-static:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-ggdb -static -D_REENTRANT -D_ASYNC -Wall -Wcast-align -march=i686 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-static:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-static -Wall -Wcast-align -fomit-frame-pointer -march=i686 -O3 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lpthread -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-icc-async:
	$(MAKE) 'CC=icc' 'CPPFLAGS=-D_ASYNC -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include -I/opt/intel/compiler50/ia32/include' 'LIBS=$(LIBS) -lpthread' 'LIBDIR=-L/usr/local/ssl/lib -L/opt/intel/compiler50/ia32/lib' _all_aes 

solaris-ultrasparc-gcc:
	$(MAKE) 'CC=gcc -mcpu=ultrasparc' 'CPPFLAGS=-O3 -D_REENTRANT' 'LIBS=$(LIBS) -lpthread -lstdc++ -lsocket -lnsl' _all_aes 

irix-64-cc:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-fullwarn -Ofast=IP27 -D_REENTRANT' 'LIBS=$(LIBS) -lpthread ' _all_aes 

irix-64-cc-async:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-D_ASYNC -fullwarn -Ofast=IP27 -D_REENTRANT' 'LIBS=$(LIBS) -lpthread' _all_aes 

irix-64-cc-debug:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-D_REENTRANT' 'DEBUG=-g2 -D_DEBUG' 'LIBS=$(LIBS) -lpthread ' _all_aes 

freebsd-x86-gcc-async:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-D_ASYNC -D_REENTRANT -Wall -Wcast-align -fomit-frame-pointer -O3' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -llthread -lstdc++ ' 'LIBDIR=-L/usr/local/lib' _all_aes 


_all_aes: $(OBJS) popt.a xml.a libaes.a
	$(CC) -o proxytest $(DEBUG) $(CPPFLAGS) $(OBJS) $(LIBDIR) $(LIBS) 

popt.a:
	cd popt;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)'

#httptunnel.a:
#	cd httptunnel;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)';
#

xml.a: 
	cd xml;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)';

libaes.a: 
	cd aes;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)';

clean:
	rm -f $(OBJS)
	cd popt; $(MAKE) clean;
#	cd httptunnel;$(MAKE) clean;
	cd xml;$(MAKE) clean;
	cd aes;$(MAKE) clean;
	rm -f proxytest
