.SUFFIXES:
.SUFFIXES: .o .cpp	

#CC=gcc
#CC=CC -mips4 -64
#CC=gcc -mcpu=ultrasparc
#INCLUDE = -I. -I/usr/local/ssl/include -I/usr/users/sya/sk13/openssl/include -I/home/imis/mix/openssl64/include -I/sun/ikt/sk13/openssl/include
INCLUDE = -I. -I/usr/users/sya/sk13/openssl/include -I/home/imis/mix/openssl64/include -I/sun/ikt/sk13/openssl/include
#LIBS	= -L/usr/local/ssl/lib -L/usr/users/sya/sk13/openssl/lib -L/home/imis/mix/openssl64/lib -L/sun/ikt/sk13/openssl/lib ./popt/popt.a ./httptunnel/httptunnel.a ./xml/xml.a -lcrypto -lpthread
LIBDIR= -L/usr/users/sya/sk13/openssl/lib -L/home/imis/mix/openssl64/lib -L/sun/ikt/sk13/openssl/lib
LIBS	= ./popt/popt.a ./xml/xml.a -lcrypto -lpthread
#CPPFLAGS =-O3 -Wall 
#CPPFLAGS =-O3 -D_REENTRANT
#DEBUG =-D_DEBUG -g
MAKE=make -f Makefile.old

OBJS_ALL=CASocket.o\
	CASocketASyncSend.o\
	CAQueue.o\
	CASocketGroup.o\
	CASocketAddr.o\
	CASocketList.o\
	CACmdLnOptions.o\
	CAMsg.o\
	CAMuxSocket.o\
	CAMuxChannelList.o\
	CASymCipher.o\
	CAASymCipher.o\
	CAInfoService.o\
	CASignature.o\
	CABase64.o\
	CAUtil.o\
	CADatagramSocket.o\
	CARoundTripTime.o\
	CAMix.o\
	CAFirstMix.o\
	CALastMix.o\
	CAMiddleMix.o\
	CALocalProxy.o\
	proxytest.o

OBJS=$(OBJS_ALL)

.cpp.o:
	$(CC) -c $(CPPFLAGS) $(INCLUDE) $(DEBUG) $< $(LDFLAGS) -o $@


all: 
	@echo 'Please select a target:'
	@echo 'linux-x86-gcc, linux-x86-gcc-static, linux-x86-gcc-debug,'
	@echo 'solaris-ultrasparc-gcc, irix-64-cc'


linux-x86-gcc:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-Wall -Wcast-align -fomit-frame-pointer -march=i686 -O3 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all 


linux-x86-gcc-prot2:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-DPROT2 -D_REENTRANT -Wall -Wcast-align -fomit-frame-pointer -march=i686 -O3 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lstdc++ ./aes/libaes.a' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-debug-prot2:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-g -D_REENTRANT -D_DEBUG -DPROT2 -Wall -Wcast-align -march=i686 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lstdc++ ./aes/libaes.a' 'LIBDIR=-L/usr/local/ssl/lib' _all_aes 

linux-x86-gcc-static:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-static -Wall -Wcast-align -fomit-frame-pointer -march=i686 -O3 -D_REENTRANT' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all 

linux-x86-gcc-debug:
	$(MAKE) 'CC=gcc' 'CPPFLAGS=-static -Wall -O0 -D_REENTRANT' 'DEBUG=-g -D_DEBUG' 'INCLUDE=-I. -I/usr/local/ssl/include' 'LIBS=$(LIBS) -lstdc++' 'LIBDIR=-L/usr/local/ssl/lib' _all 

solaris-ultrasparc-gcc:
	$(MAKE) 'CC=gcc -mcpu=ultrasparc' 'CPPFLAGS=-O3 -D_REENTRANT' 'LIBS=$(LIBS) -lstdc++ -lsocket -lnsl' _all 

irix-64-cc:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-fullwarn -Ofast=IP27 -D_REENTRANT' 'LIBS=$(LIBS)' _all 

irix-64-cc-prot2:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-DPROT2 -fullwarn -Ofast=IP27 -D_REENTRANT' 'LIBS=$(LIBS) ./aes/libaes.a' _all_aes 

irix-64-cc-debug-prot2:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-D_DEBUG -DPROT2 -fullwarn -O0 -g -D_REENTRANT' 'LIBS=$(LIBS) ./aes/libaes.a' _all_aes 

irix-64-cc-debug:
	$(MAKE) 'CC=CC -r10000 -mips4 -64' 'CPPFLAGS=-D_REENTRANT' 'DEBUG=-g2 -D_DEBUG' 'LIBS=$(LIBS)' _all 

_all: $(OBJS) popt.a xml.a
	$(CC) -o proxytest $(DEBUG) $(CPPFLAGS) $(OBJS) $(LIBDIR) $(LIBS) 

_all_aes: $(OBJS) popt.a xml.a libaes.a
	$(CC) -o proxytest $(DEBUG) $(CPPFLAGS) $(OBJS) $(LIBDIR) $(LIBS) 

popt.a:
	cd popt;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)'

httptunnel.a:
	cd httptunnel;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)';

xml.a: 
	cd xml;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)';

libaes.a: 
	cd aes;$(MAKE) 'CC=$(CC)' 'DEBUG=$(DEBUG)' 'INCLUDE=$(INCLUDE)' 'CPPFLAGS=$(CPPFLAGS)';

clean:
	rm -f $(OBJS)
	cd popt; $(MAKE) clean;
	cd httptunnel;$(MAKE) clean;
	cd xml;$(MAKE) clean;
	cd aes;$(MAKE) clean;
	rm -f proxytest
