libxml.a: xmloutput.cpp xmlinput.cpp xmlinput_c.cpp  
	$(CC) -c  $(CPPFLAGS) $(INCLUDE) $(DEBUG) xmloutput.cpp -o xmloutput.o
	$(CC) -c  $(CPPFLAGS) $(INCLUDE) $(DEBUG) xmlinput.cpp -o xmlinput.o
	$(CC) -c  $(CPPFLAGS) $(INCLUDE) $(DEBUG) xmlinput_c.cpp -o xmlinput_c.o
	ar -rcs libxml.a *.o 

clean:
	rm -f *.o
	rm -f libxml.a

