version: '3'
services:
  anon-web-proxy:
    build:
      context: ./
      dockerfile: ANONWebProxy.dockerfile
    image: docker.securecloud.works:443/anon-web-proxy:latest
  anon-socks-proxy:
    build:
      context: ./
      dockerfile: ANONSocksProxy.dockerfile
    image: docker.securecloud.works:443/anon-socks-proxy:latest  
  mix:
    build:
      context: ./
      dockerfile: mix.dockerfile
    image: anon-mix:latest  
  firstmix:
    build:
      context: ./
      dockerfile: firstmix.dockerfile
    image: docker.securecloud.works:443/anon-mix-firstmix:latest  
  middlemix:
    build:
      context: ./
      dockerfile: middlemix.dockerfile
    image: docker.securecloud.works:443/anon-mix-middlemix:latest  
  lastmix:
    build:
      context: ./
      dockerfile: lastmix.dockerfile
    image: docker.securecloud.works:443/anon-mix-lastmix:latest  
